### ISSUE TITLE
启动优化

### ISSUE THREAD

**Issue by Yuan91** [lyandy/Linked_Order_Analyze#1]
哈喽，在知乎上看到脉脉团队的文章 https://zhuanlan.zhihu.com/p/396550853
请问文章里提到的load方法监测的工具开源了吗

**Comment by lyandy** [comment]
> 



> 哈喽，在知乎上看到脉脉团队的文章 https://zhuanlan.zhihu.com/p/396550853
> 请问文章里提到的load方法监测的工具开源了吗

https://github.com/tripleCC/Laboratory/tree/master/HookLoadMethods
